### ISSUE TITLE
Add command groups access conditions

### ISSUE THREAD

**Issue by lbureau-billettiqueservices** [lbureau-billettiqueservices/GT4_support_schema#8]
Add a simple decoding of `access_conditions` and `key_indexes` to regroup data by command group.

Example, given these:

```json
{
    "access_conditions": "1F121212",
    "key_indexes": "01020302",
}
```

it would be possible to have instead

```json
{
    "cmd_group": {
        "00": {
            "access_condition": "1F"
            "key_index": "01" 
        },
        "01": {
            "access_condition": "12"
            "key_index": "03" 
        },
        "02": {
            "access_condition": "12"
            "key_index": "03" 
        },
        "03": {
            "access_condition": "12"
            "key_index": "02" 
        },
    }
}
```

There is no way to ensure the integrity of data between the "raw" fields `access_conditions` and `key_indexes`, and these fields should be optionals.

Edit after comment: removed `access_conditions` and `key_indexes` in new format.

**Comment by Spirtech-GT4** [comment]
I agree that there should be only one way to describe the access rights, otherwise there would be risks of inconsistency.
And I would rather choose the detailed format (i.e. removing access_conditions/key_indexes and keeping cmd_group).

**Comment by lbureau-billettiqueservices** [comment]
> And I would rather choose the detailed format (i.e. removing access_conditions/key_indexes and keeping cmd_group).

I was about to say that i like keeping the raw data from the FCP in `key_indexes`and `access_conditions` but i realized we already give the full FCP in the dump as a required field.

There would be indeed no point in keeping both "interpretations".

**Comment by lbureau-billettiqueservices** [comment]
I said that it's not possible to ensure integrity of data, but it would be possible to ensure that `cmd_group` if present contains exactly the groups `00`, `01`, `02` and `03`, which at least ensures that everything was decoded from the FCP. Would that be enough?

**Comment by Spirtech-GT4** [comment]
Done, issue to be closed?

**Comment by lbureau-billettiqueservices** [comment]
It indeed should be closed!
